-- MySQL Script generated by MySQL Workbench
-- Thu Oct  7 21:18:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Easy-Parking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Easy-Parking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Easy-Parking` DEFAULT CHARACTER SET utf8 ;
USE `Easy-Parking` ;

-- -----------------------------------------------------
-- Table `Easy-Parking`.`Plaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`Plaza` (
  `idPlaza` INT NOT NULL,
  `Plazacol` TINYINT NULL,
  PRIMARY KEY (`idPlaza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Easy-Parking`.`Tipo_Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`Tipo_Vehiculo` (
  `idTipo_Vehiculo` INT NOT NULL,
  `Codigo_Tipo` INT NULL,
  `Nombre_Tipo` VARCHAR(45) NULL,
  `Tarifa` DOUBLE NULL,
  PRIMARY KEY (`idTipo_Vehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Easy-Parking`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`Vehiculo` (
  `Id_placa` INT NOT NULL,
  `Placa` VARCHAR(45) NULL,
  `Fecha_ingreso` DATETIME NULL,
  `Fecha_salida` DATETIME NULL,
  PRIMARY KEY (`Id_placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Easy-Parking`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`Factura` (
  `idFactura` INT NOT NULL,
  `Costo` DOUBLE NULL,
  `Fecha_expedicion` DATETIME NULL,
  `Facturacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Easy-Parking`.`PLAZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`PLAZA` (
  `id_Plaza` INT NOT NULL,
  `disponibilidad` BIT(2) NULL,
  PRIMARY KEY (`id_Plaza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Easy-Parking`.`TIPO_VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`TIPO_VEHICULO` (
  `id_Tipo_Vehiculo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(15) NOT NULL,
  `tarifa` DECIMAL(6) NOT NULL,
  PRIMARY KEY (`id_Tipo_Vehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Easy-Parking`.`VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`VEHICULO` (
  `id_Vehiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `fecha_salida` DATETIME NULL,
  `tipo_vehiculo` INT NULL,
  `id_plaza` INT NULL,
  `TIPO_VEHICULO_id_Tipo_Vehiculo` INT NOT NULL,
  `PLAZA_id_Plaza` INT NOT NULL,
  PRIMARY KEY (`id_Vehiculo`),
  INDEX `fk_VEHICULO_TIPO_VEHICULO1_idx` (`TIPO_VEHICULO_id_Tipo_Vehiculo` ASC) VISIBLE,
  INDEX `fk_VEHICULO_PLAZA1_idx` (`PLAZA_id_Plaza` ASC) VISIBLE,
  CONSTRAINT `idVehiculo`
    FOREIGN KEY ()
    REFERENCES `Easy-Parking`.`Tipo_Vehiculo` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEHICULO_TIPO_VEHICULO1`
    FOREIGN KEY (`TIPO_VEHICULO_id_Tipo_Vehiculo`)
    REFERENCES `Easy-Parking`.`TIPO_VEHICULO` (`id_Tipo_Vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEHICULO_PLAZA1`
    FOREIGN KEY (`PLAZA_id_Plaza`)
    REFERENCES `Easy-Parking`.`PLAZA` (`id_Plaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Easy-Parking`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Easy-Parking`.`FACTURA` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE NOT NULL,
  `Fecha_expedicion` DATETIME NOT NULL,
  `id_vehiculo` INT NULL,
  `VEHICULO_id_Vehiculo` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_FACTURA_VEHICULO1_idx` (`VEHICULO_id_Vehiculo` ASC) VISIBLE,
  CONSTRAINT `Vehiculo`
    FOREIGN KEY ()
    REFERENCES `Easy-Parking`.`Plaza` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURA_VEHICULO1`
    FOREIGN KEY (`VEHICULO_id_Vehiculo`)
    REFERENCES `Easy-Parking`.`VEHICULO` (`id_Vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Easy-Parking` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `Easy-Parking`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
